env:
  global:
    - CC_TEST_REPORTER_ID=8323225e297d5a51bce7700c32894323f70a9fda90d2a297d4fc29afc5ab512e
language: ruby
rvm:
  - 2.7.2
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
before_install:
  - cp config/database.yml.travis config/database.yml
install:
  - nvm install --lts
  - bundle install --jobs=3 --retry=3
  - yarn
before_script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
